---
roles:
  - name: prometheus
    src: https://github.com/prometheus-community/ansible.git
    version: "0.6.0"

  - name: initial
    src: https://github.com/expo-lux/ansible_initial.git
    version: "0.1.3"

collections:
  - name: community.general
    version: "5.7.0"
  
  - name: ansible.posix
    version: "1.4.0"

  - name: community.crypto
    version: "2.5.0"
...
