---
roles:
  - name: initial
    src: https://github.com/expo-lux/ansible_initial.git
    version: "0.1.3"

  - name: mysql
    src: https://github.com/geerlingguy/ansible-role-mysql.git
    version: "4.3.3"