grafana_security:
  admin_user: admin
  admin_password: "secretpassword"
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://localhost:9090'
    basicAuth: false  