---
  - name: Kill unattended-upgrades process
    shell: "pgrep unattended | xargs -r kill -9"

  - name: Stop thrash services
    systemd:
      state: stopped
      name: "{{ item }}"
      enabled: no
    loop:
      - cloud-config
      - cloud-final
      - cloud-init-local
      - cloud-init

  - include_tasks: debian.yml
    when: ansible_os_family == 'Debian'

  - include_tasks: redhat.yml
    when: ansible_os_family == 'RedHat'
  
  - name: Remove droplet-agent job from cron
    file:
      path: /etc/cron.hourly/droplet-agent
      state: absent 

  - name: Set timezone 
    community.general.timezone:
      name: Europe/Moscow
    notify: restart rsyslog
    
  - name: Flush handlers
    meta: flush_handlers



